import globals from "globals";
import pluginJs from "@eslint/js";

export default [
  {
    files: ["**/*.js"],
    languageOptions: {
      sourceType: "commonjs",
      globals: globals.browser // Add global variables
    },
    rules: {
      // Airbnb Rules
      "comma-dangle": ["error", "never"],
      "no-cond-assign": ["error", "always"],
      "no-console": "off",
      "no-constant-condition": ["error", { "checkLoops": false }],
      "no-control-regex": "off",
      "no-debugger": "error",
      "no-dupe-args": "error",
      "no-dupe-keys": "error",
      "no-duplicate-case": "error",
      "no-empty-character-class": "error",
      "no-empty": ["error", { "allowEmptyCatch": true }],
      "no-ex-assign": "error",
      "no-extra-boolean-cast": "error",
      "no-extra-parens": ["error", "all", { "nestedBinaryExpressions": false }],
      "no-extra-semi": "error",
      "no-func-assign": "error",
      "no-inner-declarations": ["error", "both"],
      "no-invalid-regexp": "error",
      "no-irregular-whitespace": "error",
      "no-obj-calls": "error",
      "no-prototype-builtins": "off",
      "no-regex-spaces": "error",
      "no-sparse-arrays": "error",
      "no-template-curly-in-string": "error",
      "no-unexpected-multiline": "error",
      "no-unreachable": "error",
      "no-unsafe-finally": "error",
      "no-unsafe-negation": "error",
      "use-isnan": "error",
      "valid-typeof": ["error", { "requireStringLiterals": true }],
      "array-callback-return": "error",
      "block-scoped-var": "error",
      "consistent-return": "error",
      "curly": ["error", "all"],
      "default-case": "error",
      "dot-location": ["error", "property"],
      "dot-notation": "error",
      "eqeqeq": ["error", "always"],
      "guard-for-in": "error",
      "no-caller": "error",
      "no-case-declarations": "error",
      "no-empty-function": "error",
      "no-empty-pattern": "error",
      "no-eval": "error",
      "no-extend-native": "error",
      "no-extra-bind": "error",
      "no-extra-label": "error",
      "no-fallthrough": "error",
      "no-global-assign": "error",
      "no-implicit-coercion": "error",
      "no-implicit-globals": "error",
      "no-implied-eval": "error",
      "no-invalid-this": "error",
      "no-iterator": "error",
      "no-labels": "error",
      "no-lone-blocks": "error",
      "no-loop-func": "error",
      "no-magic-numbers": "off",
      "no-multi-spaces": "error",
      "no-multi-str": "error",
      "no-new-func": "error",
      "no-new-wrappers": "error",
      "no-new": "error",
      "no-octal-escape": "error",
      "no-octal": "error",
      "no-param-reassign": "error",
      "no-proto": "error",
      "no-redeclare": "error",
      "no-restricted-properties": "error",
      "no-return-assign": ["error", "always"],
      "no-return-await": "error",
      "no-script-url": "error",
      "no-self-assign": "error",
      "no-self-compare": "error",
      "no-sequences": "error",
      "no-throw-literal": "error",
      "no-unmodified-loop-condition": "error",
      "no-unused-expressions": "error",
      "no-unused-labels": "error",
      "no-useless-call": "error",
      "no-useless-catch": "error",
      "no-useless-concat": "error",
      "no-useless-escape": "error",
      "no-useless-return": "error",
      "no-void": "error",
      "no-warning-comments": "error",
      "no-with": "error",
      "prefer-promise-reject-errors": "error",
      "radix": "error",
      "require-await": "error",
      "vars-on-top": "error",
      "wrap-iife": ["error", "outside"],
      "yoda": "error",
      "strict": ["error", "never"],
      "init-declarations": ["error", "always"],
      "no-catch-shadow": "error",
      "no-delete-var": "error",
      "no-label-var": "error",
      "no-restricted-globals": "error",
      "no-shadow-restricted-names": "error",
      "no-shadow": "error",
      "no-undef-init": "error",
      "no-undef": "error",
      "no-undefined": "error",
      "no-unused-vars": "error",
      "no-use-before-define": "error",
      "callback-return": "error",
      "global-require": "error",
      "handle-callback-err": "error",
      "no-mixed-requires": "error",
      "no-new-require": "error",
      "no-path-concat": "error",
      "no-process-env": "error",
      "no-process-exit": "error",
      "no-restricted-modules": "error",
      "no-sync": "error",
      "array-bracket-newline": "off",
      "array-bracket-spacing": ["error", "never"],
      "array-element-newline": "off",
      "block-spacing": "error",
      "brace-style": "off",
      "camelcase": "error",
      "capitalized-comments": "off",
      "comma-spacing": ["error", { "before": false, "after": true }],
      "comma-style": ["error", "last"],
      "computed-property-spacing": ["error", "never"],
      "consistent-this": "off",
      "func-call-spacing": ["error", "never"],
      "func-name-matching": "off",
      "func-names": "off",
      "func-style": "off",
      "function-call-argument-newline": "off",
      "function-paren-newline": "off",
      "id-blacklist": "off",
      "id-length": "off",
      "id-match": "off",
      "implicit-arrow-linebreak": "off",
      "indent": ["error", 2, { "SwitchCase": 1 }],
      "jsx-quotes": ["error", "prefer-double"],
      "key-spacing": ["error", { "beforeColon": false, "afterColon": true, "mode": "strict" }],
      "keyword-spacing": ["error", { "before": true, "after": true }],
      "line-comment-position": "off",
      "linebreak-style": ["error", "unix"],
      "lines-around-comment": "off",
      "lines-between-class-members": ["error", "always", { "exceptAfterSingleLine": true }],
      "max-classes-per-file": "off",
      "max-depth": "off",
      "max-len": ["error", { "code": 120, "ignoreComments": true, "ignoreUrls": true }],
      "max-lines": "off",
      "max-nested-callbacks": "off",
      "max-params": "off",
      "max-statements-per-line": ["error", { "max": 1 }],
      "max-statements": "off",
      "multiline-comment-style": "off",
      "multiline-ternary": "off",
      "new-cap": "error",
      "new-parens": "error",
      "newline-per-chained-call": "off",
      "no-array-constructor": "error",
      "no-bitwise": "error",
      "no-continue": "off",
      "no-inline-comments": "off",
      "no-lonely-if": "error",
      "no-mixed-operators": "off",
      "no-mixed-spaces-and-tabs": "error",
      "no-multi-assign": "off",
      "no-multiple-empty-lines": ["error", { "max": 2, "maxEOF": 0, "maxBOF": 0 }],
      "no-negated-condition": "off",
      "no-nested-ternary": "off",
      "no-new-object": "error",
      "no-plusplus": "off",
      "no-restricted-syntax": "off",
      "no-tabs": "error",
      "no-ternary": "off",
      "no-trailing-spaces": "error",
      "no-underscore-dangle": "off",
      "no-unneeded-ternary": "error",
      "no-whitespace-before-property": "error",
      "nonblock-statement-body-position": "off",
      "object-curly-newline": "off",
      "object-curly-spacing": ["error", "always"],
      "object-property-newline": "off",
      "one-var-declaration-per-line": "off",
      "one-var": "off",
      "operator-assignment": "off",
      "operator-linebreak": ["error", "after"],
      "padded-blocks": ["error", "never"],
      "padding-line-between-statements": "off",
      "prefer-exponentiation-operator": "off",
      "prefer-object-spread": "error",
      "quote-props": ["error", "as-needed", { "keywords": true, "unnecessary": true, "numbers": true }],
      "quotes": ["error", "single", { "avoidEscape": true, "allowTemplateLiterals": false }],
      "require-jsdoc": "off",
      "semi-spacing": ["error", { "before": false, "after": true }],
      "semi-style": ["error", "last"],
      "semi": ["error", "always"],
      "sort-keys": "off",
      "sort-vars": "off",
      "space-before-blocks": "error",
      "space-before-function-paren": ["error", { "anonymous": "always", "named": "never", "asyncArrow": "always" }],
      "space-in-parens": ["error", "never"],
      "space-infix-ops": "error",
      "space-unary-ops": ["error", { "words": true, "nonwords": false }],
      "spaced-comment": ["error", "always", { "exceptions": ["-", "+"] }],
      "switch-colon-spacing": "error",
      "template-tag-spacing": ["error", "never"],
      "unicode-bom": ["error", "never"],
      "wrap-regex": "off",
      "arrow-body-style": "off",
      "arrow-parens": ["error", "as-needed"],
      "arrow-spacing": ["error", { "before": true, "after": true }],
      "constructor-super": "error",
      "generator-star-spacing": ["error", { "before": true, "after": false }],
      "no-class-assign": "error",
      "no-confusing-arrow": ["error", { "allowParens": true }],
      "no-const-assign": "error",
      "no-dupe-class-members": "error",
      "no-duplicate-imports": ["error", { "includeExports": true }],
      "no-new-symbol": "error",
      "no-restricted-imports": "off",
      "no-this-before-super": "error",
      "no-useless-computed-key": "error",
      "no-useless-constructor": "error",
      "no-useless-rename": "error",
      "no-var": "error",
      "object-shorthand": ["error", "always", { "ignoreConstructors": false, "avoidQuotes": true }],
      "prefer-arrow-callback": "error",
      "prefer-const": "error",
      "prefer-destructuring": ["error", { "object": true, "array": false }],
      "prefer-numeric-literals": "error",
      "prefer-rest-params": "error",
      "prefer-spread": "error",
      "prefer-template": "error",
      "require-yield": "error",
      "rest-spread-spacing": ["error", "never"],
      "sort-imports": "off",
      "symbol-description": "error",
      "template-curly-spacing": ["error", "never"],
      "yield-star-spacing": ["error", { "before": true, "after": false }]
    }
  },
  pluginJs.configs.recommended
];
